M48
; DRILL file KiCad 10.0.3 date 2026-07-20T10:22:46
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-20T10:22:46-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X92.39Y-82.535
X92.39Y-88.315
T2
X104.4Y-101.5
X105.0Y-173.3
M30
